### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Spootacular** [Mnemosyne-20/Mnemosyne-2.0-1#14]
- [x] website needs to be added
- [x] hosting the clickonce application without letting userIDS and personal info through
- [x] finishing up patching comment handling atm
- [ ] more things for the TODO, such as possibly checking for mass numbers of reposts using machine learning, which would be interesting to develop and to try to learn
- [x] We need a method to get all posts within a timeframe (say, past 3 days), so that we can work on those alone as to further get all comments
- [x] Add SQLITE3 so that we have a pageable public database of all archives
- [ ] some form of auto install, idrc if it's powershell, clickonce, bash, what have you, we just need it done

**Comment by chuggafan** [comment]
Going to close number 2 as that's the last number, i just realised

**Comment by chuggafan** [comment]
We need to add checking for recently edited comments too, but i'm not sure how :(
