### ISSUE TITLE
Configuration file TODO list

### ISSUE THREAD

**Issue by chuggafan** [Mnemosyne-20/Mnemosyne-2.0-1#16]
- [ ] Get it all into a way we can unit test, so we need to package everything into separate libraries that deserve, such as the config files
- [ ] get it into a way we can test it on strings currently
- [ ] forcibly port every config file to the new format and overwrite the old one
